[workspace]
resolver = "2"
members = [
    "app",
    "desktop",
    "drivers/bq25895",
    "drivers/cy8cmbr3116",
    "firmware",
    "libs/display_renderer",
    "libs/display_types",
    "libs/embedded_tools",
    "libs/emulator",
    "libs/procmacros",
    "sdk",
    "uploader",
]

[profile.release]
lto = true
opt-level = 'z'
