[package]
name = "esp32s3-embedded-tools"
version = "0.1.0"
edition = "2024"
authors = ["Chris Dell <cjdell@gmail.com>"]
description = "ESP32-S3 specific trait implementations"

[dependencies]
defmt = "1.0.1"
block_device = "0.1.3"
littlefs-rust = "0.1.0"

embedded-tools = { path = "../embedded_tools" }

embassy-sync = { version = "0.7.2" }
esp-storage = { git = "https://github.com/esp-rs/esp-hal.git", features = ["esp32s3"] }
embedded-storage = "0.3.1"
