[package]
name = "sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm_protocol = { path = "../libs/wasm_protocol" }
serde_json = { version = "1.0.149", default-features = false, features = ["alloc"] }
serde-json-core = "0.6.0"
lol_alloc = "0.4.1"
embassy-sync = "0.7.2"
static_cell = "2.1.1"
makepad-zune-jpeg = { version = "0.3.17", default-features = false }
