[package]
name = "uploader"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs"] }
reqwest = { version = "0.12", default-features = false, features = ["stream", "rustls-tls"] }
futures-util = "0.3"
tokio-util = { version = "0.7", features = ["io"] }
indicatif = "0.17"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
mime_guess = "2"

[profile.release]
opt-level = 3
